#allowlist: [12345,12346]
denylist: [12345,12346]

#AI配置
aiInclude: [] # 对话群聊
chatLong: 50 # 对话长度
temperature: 1.3
Embedding:
  apiKey: '' # 前去 https://api.bltcy.ai/ 购买api-key
  baseURL: 'https://api.bltcy.ai/v1/'
  model: 'text-embedding-3-small'
Chat:
  apiKey: '' # 前去 https://platform.deepseek.com/ 购买api-key
  baseURL: 'https://api.deepseek.com'
  model: '' 
  index: 1